---
title: jQuery
output: 
  tufte::tufte_html:
    self_contained: no
    css: local.css
  html_document: 
    self_contained: no
---

**jQuery** is a [cross-platform](cross-platform "wikilink") [JavaScript library](JavaScript_library "wikilink") designed to simplify the [client-side scripting](client-side_scripting "wikilink") of [HTML](HTML "wikilink"). jQuery is the most popular JavaScript library in use today, with installation on 65% of the top 10 million highest-trafficked sites on the Web. jQuery is [free, open-source software](free_and_open_source_software "wikilink") licensed under the [MIT License](MIT_License "wikilink").

jQuery's syntax is designed to make it easier to navigate a document, select [DOM](Document_Object_Model "wikilink") elements, create [animations](animation "wikilink"), handle [events](event_(computing) "wikilink"), and develop [Ajax](Ajax_(programming) "wikilink") applications. jQuery also provides capabilities for developers to create [plug-ins](plug-in_(computing) "wikilink") on top of the JavaScript library. This enables developers to create [abstractions](abstraction_(computer_science) "wikilink") for low-level interaction and animation, advanced effects and high-level, themeable widgets. The modular approach to the jQuery library allows the creation of powerful [dynamic web pages](dynamic_web_page "wikilink") and Web applications.

The set of [jQuery core features](#Features "wikilink")—DOM element selections, traversal and manipulation—enabled by its *selector engine* (named "Sizzle" from v1.3), created a new "programming style", fusing algorithms and DOM data structures. This style influenced the architecture of other [JavaScript frameworks](Comparison_of_JavaScript_frameworks "wikilink") like [YUI v3](YUI_Library "wikilink") and [Dojo](Dojo_Toolkit "wikilink"), later stimulating the creation of the standard *Selectors API*.

[Microsoft](Microsoft "wikilink") and [Nokia](Nokia "wikilink") bundle jQuery on their platforms. Microsoft includes it with [Visual Studio](Microsoft_Visual_Studio "wikilink") for use within Microsoft's [ASP.NET AJAX](ASP.NET_AJAX "wikilink") and [ASP.NET MVC](ASP.NET_MVC "wikilink") frameworks while Nokia has integrated it into the Web Run-Time widget development platform. jQuery has also been used in [MediaWiki](MediaWiki "wikilink") since version 1.16.

## Overview

jQuery, at its core, is a **DOM** ([Document Object Model](Document_Object_Model "wikilink")) manipulation library. The DOM is a tree-structure representation of all the elements of a Web page and jQuery simplifies the syntax for finding, selecting, and manipulating these DOM elements. For example, jQuery can be used for finding an element in the document with a certain property (e.g. all elements with an [h1](HTML_element#heading "wikilink") tag), changing one or more of its attributes (e.g. color, visibility), or making it respond to an event (e.g. a mouse click).

jQuery also provides a paradigm for event handling that goes beyond basic DOM element selection and manipulation. The event assignment and the event callback function definition are done in a single step in a single location in the code. jQuery also aims to incorporate other highly used JavaScript functionality (e.g. fade ins and fade outs when hiding elements, animations by manipulating [CSS](Cascading_Style_Sheets "wikilink") properties).

The principles of developing with jQuery are:

-   **Separation of JavaScript and HTML**: The jQuery library provides simple syntax for adding [event](Event_(computing) "wikilink") handlers to the [DOM](Document_Object_Model "wikilink") using JavaScript, rather than adding [HTML event attributes](HTML_attribute#Event_attributes "wikilink") to call JavaScript functions. Thus, it encourages developers to [completely separate](Separation_of_concerns "wikilink") JavaScript code from HTML markup.
-   **Brevity and clarity**: jQuery promotes brevity and clarity with features like chainable functions and shorthand function names.
-   **Elimination of cross-browser incompatibilities**: The JavaScript engines of different browsers differ slightly so JavaScript code that works for one browser may not work for another. Like other JavaScript toolkits, jQuery handles all these cross-browser inconsistencies and provides a consistent interface that works across different browsers.
-   **Extensibility**: New events, elements, and methods can be easily added and then reused as a plugin.

## Features

jQuery includes the following features:

-   [DOM](Document_Object_Model "wikilink") element selections using the multi-browser open source selector engine *Sizzle*, a spin-off of the jQuery project
-   DOM manipulation based on CSS selectors that uses elements' names and attributes, such as id and class, as criteria to select nodes in the DOM
-   Events
-   Effects and animations
-   [Ajax](Ajax_(programming) "wikilink")
-   [Deferred and Promise](Futures_and_promises "wikilink") objects to control asynchronous processing
-   [JSON](JSON "wikilink") parsing
-   [Extensibility](Extensibility "wikilink") through plug-ins
-   Utilities, such as feature detection
-   Compatibility methods that are natively available in modern browsers, but need fall backs for older ones, such as `inArray()` and `each()`
-   Multi-browser (not to be confused with [cross-browser](cross-browser "wikilink")) support

## Usage

### Including the library

The jQuery library is a single JavaScript file containing all of its common DOM, event, effects, and Ajax functions. It can be included within a Web page by linking to a local copy or to one of the many copies available from public servers. jQuery has a [content delivery network](content_delivery_network "wikilink") (CDN) hosted by [MaxCDN](https://www.maxcdn.com/). Google and Microsoft host it as well.

``` {.html5}
<script src="jquery.js"></script>
```

It is also possible to include jQuery directly from a CDN:

``` {.html5}
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
```

### Usage styles

jQuery has two usage styles:

-   Via the `$` function, which is a [factory method](Factory_method_pattern "wikilink") for the jQuery object. These functions, often called *commands*, are [*chainable*](method_chaining "wikilink") as they all return jQuery objects.
-   Via `$.`-prefixed functions. These are *utility functions*, which do not act upon the jQuery object directly.

Access to and manipulation of multiple DOM nodes in jQuery typically begins with calling the `$` function with a CSS selector string. This returns a jQuery object referencing all the matching elements in the [HTML](HTML "wikilink") page. `$("div.test")`, for example, returns a jQuery object with all the `div` elements of class `test`. This node set can be manipulated by calling methods on the returned jQuery object or on the nodes themselves.

### No-conflict mode

jQuery also includes `.noConflict()` mode, which relinquishes control of `$`. This is helpful if jQuery is used with other libraries that also use `$` as an identifier. In no-conflict mode, developers can use `jQuery` as a replacement for `$` without losing functionality.

### Typical start-point

Typically, jQuery is used by putting initialization code and event handling functions in `$(`*`handler`*`)`. This is triggered when the browser has constructed the DOM and sends a load event.

```javascript
$(function () {
        // jQuery code, event handling callbacks here
});
```

Historically, `$(document).ready(callback)` has been the de facto signature for running code when the DOM is ready. However, since jQuery 3.0, developers are encouraged to use the much shorter `$(handler)` signature.

Callback functions for event handling on elements that aren't loaded yet can be registered inside `.ready()` as [anonymous functions](Anonymous_function#JavaScript "wikilink"). These event handlers will only be called when the event is triggered. For example, the following code adds an event handler for a mouse click on an `img` image element.

```javascript
$(function () {
        $('img').on('click', function () {
              // handle the click event on any img element in the page
        });
});
```

The following syntaxes are equivalent, although only `$(`*`handler`*`)` should be used:

-   `$(`*`handler`*`)`
-   `$().ready(`*`handler`*`)`
-   `$(document).ready(`*`handler`*`)`
-   `$("selector").ready(`*`handler`*`)`

### Chaining

jQuery commands typically return a jQuery object, so commands can be chained:

```javascript
$('div.test').add('p.quote').addClass('blue').slideDown('slow');
```

This line finds the union of all `div` tags with class attribute `test` and all `p` tags with class attribute `quote`, adds the class attribute `blue` to each matched element, and then increases their height with an animation. The `$` and `add` functions affect the matched set, while the `addClass` and `slideDown` affect the referenced nodes.

Certain jQuery functions return specific values (such as `$('#input-user-email').val()`). In these cases, chaining will not work as the value does not reference the jQuery object.

### Creating new DOM elements

Besides accessing DOM nodes through jQuery object hierarchy, it is also possible to create new DOM elements, if a string passed as the argument to \$() looks like HTML. For example, this line finds an HTML `select` element with ID `carmakes`, and adds an `option` element with value "VAG" and text "Volkswagen":

```javascript
$('select#carmakes').append($('<option />').attr({value:"VAG"}).append("Volkswagen"));
```

### Utility functions

Functions prefixed with `$.` are utility functions or functions that affect global properties and behaviour. The following, for example, is a function used for iterating over arrays called `each` in jQuery:

```javascript
$.each([1,2,3], function() {
  console.log(this + 1);
});
```

This writes "2", "3", "4" to the console.

### Ajax

It is possible to perform [cross-browser](cross-browser "wikilink") [Ajax](Ajax_(programming) "wikilink") requests using `$.ajax`. Its associated methods can be used to load and manipulate remote data.

```javascript
$.ajax({
  type: 'POST',
  url: '/process/submit.php',
  data: {
    name : 'John',
    location : 'Boston',
  },
}).done(function(msg) {
  alert('Data Saved: ' + msg);
}).fail(function(xmlHttpRequest, statusText, errorThrown) {
  alert(
    'Your form submission failed.\n\n'
      + 'XML Http Request: ' + JSON.stringify(xmlHttpRequest)
      + ',\nStatus Text: ' + statusText
      + ',\nError Thrown: ' + errorThrown);
});
```

This example posts the data `name=John` and `location=Boston` to `/process/submit.php` on the server. When this request finishes the success function is called to alert the user. If the request fails it will alert the user to the failure, the status of the request, and the specific error.

#### Asynchronous

Note that the above example uses the deferred nature of `$.ajax()` to handle its asynchronous nature: `.done()` and `.fail()` create callbacks that run only when the asynchronous process is complete.

## jQuery plug-ins

jQuery's architecture allows developers to create [plug-in](Plug-in_(computing) "wikilink") code to extend its function. There are thousands of jQuery plug-ins available on the Web that cover a range of functions, such as Ajax helpers, [Web services](Web_service "wikilink"), datagrids, dynamic lists, [XML](XML "wikilink") and [XSLT](XSLT "wikilink") tools, [drag and drop](drag_and_drop "wikilink"), events, [cookie](HTTP_cookie "wikilink") handling, and [modal windows](modal_window "wikilink").

An important source of jQuery plug-ins is the plugins subdomain of the jQuery Project website. The plugins in this subdomain, however, were accidentally deleted in December 2011 in an attempt to rid the site of spam. The new site will include a [GitHub](GitHub "wikilink")-hosted repository, which will require developers to resubmit their plugins and to conform to new submission requirements. There are alternative plug-in search engines like [jquer.in](http://jquer.in) that take more specialized approaches, such as listing only plug-ins that meet certain criteria (e.g. those that have a public code repository). jQuery provides a "Learning Center" that can help users understand JavaScript and get started developing jQuery plugins.


## Testing framework

[QUnit](QUnit "wikilink") is a [test automation framework](test_automation_framework "wikilink") used to test the jQuery project. The jQuery team developed it as an in-house unit testing library. The jQuery team uses it to test its code and plugins, but it can test any generic JavaScript code, including server-side JavaScript code.

As of 2011, the jQuery Testing Team uses [QUnit](QUnit "wikilink") with [TestSwarm](TestSwarm "wikilink") to test each jQuery codebase release.

## See also

-   [Comparison of JavaScript frameworks](Comparison_of_JavaScript_frameworks "wikilink")
-   [jQuery Mobile](jQuery_Mobile "wikilink")
-   [jQuery UI](jQuery_UI "wikilink")
-   [Globalize](Globalize "wikilink")
